server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: diPtMOfy4jAJgivXLRDX1lXYgk1MAK7q
            redirect-uri: http://localhost:8081/client
            client-name: oauth2-client-app
            authorization-grant-type: password
            client-authentication-method: client_secret_basic
#            scope: openid, profile

#          keycloak:
#            client-id: oauth2-client-app
#            client-secret: diPtMOfy4jAJgivXLRDX1lXYgk1MAK7q
#            client-name: oauth2-client-app
#            authorization-grant-type: client_credentials
#            client-authentication-method: client_secret_post

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
